### ISSUE TITLE
[Suggestion] Specific message for incorrect decryption password

### ISSUE THREAD

**Issue by Cade66** [mprimi/portable-secret#12]
Hi,

Nice work:
Maybe a suggestion for delivering a specific message when the entered  decryption password is incorrect:
Instead of `Decryption failed: OperationError: The operation failed for an operation-specific reason` something like a basic `Wrong password, try again!`

When testing my first thought was that the failure was that of the code itself ...

**Comment by mprimi** [comment]
Error in decryption throws a generic error. I cannot tell with certainty the password was wrong.

It's possible that it's by design. And from what I remember the error may even be browser-specific.

That said,  I'm a total noob with Javascript, if anyone has suggestions on improving error handling in general I'd appreciate it.
