### ISSUE TITLE
Creator fails on Chrome for CORS policy

### ISSUE THREAD

**Issue by MaggieLeber** [mprimi/portable-secret#8]
`Access to fetch at 'file:///D:/Users/maggie/Google%20Drive/portable-secret/creator/secret-template.html' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.`

**Comment by mprimi** [comment]
The [README in the creator folder] explains you need to run an HTTPS server locally for the creator (secrets don't require a server to extract).

@Unkn0wnCreator method also works. I didn't take this route because this is harder for people to grok. But the actual creator I use for personal use embeds the strings in a similar way.

**Comment by MaggieLeber** [comment]
Ah... Didn't get that the creator won't run standalone. Makes sense.
